name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: my-devops-cicd-demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names ${{ vars.ECR_REPOSITORY }} \
          || aws ecr create-repository --repository-name ${{ vars.ECR_REPOSITORY }}

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.get_version.outputs.VERSION }}"
          LATEST=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest"
          docker build -t $IMAGE_URI -t $LATEST.
          docker push $IMAGE_URI